### ISSUE TITLE
jump to wrong line

### ISSUE THREAD

**Issue by nickelchen** [jstemmer/gotags#32]
when using tagbar(latest version from master) with gotags (latest version from brew) to display go project tags, it jumps to wrong line of the source file. 
most projects works just fine, but the following test project tags are always messing up.
```
https://github.com/hashicorp/serf
```
specificly is this file:  `cmd/serf/command/agent/ipc.go`

I dont know which one's bug (gotags or tagbar), so issued it here. 
Thank you.

**Comment by jstemmer** [comment]
This sounds similar to #31. Tagbar jumps to the correct line if you remove the `^` character from lines 689, 696 and 701. The `gotags` output is the same in either case, so this sounds like a bug in Tagbar.

**Comment by nickelchen** [comment]
HI @jstemmer  , I've  tried what you say,  it works fine now.
