### ISSUE TITLE
Kinds: 'i' for interface, 'c' for class, 'n' for namespace

### ISSUE THREAD

**Issue by chenpengcheng** [jstemmer/gotags#35]
https://github.com/jstemmer/gotags/blob/3751bad226c4308b3812a362ffda82e40de731ac/tag.go#L42

**Comment by jstemmer** [comment]
Some more information would be helpful. I don't think this should be changed unless it's causing problems somewhere.

**Comment by blockchainian** [comment]
Same kind letter has different meanings for different languges. It would be nice if we could follow convention. Below is what the kind letters mean in older languages:

$ ctags --list-kinds |egrep ' i | c | n ' | sort
    c  chapters
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes
    c  classes 
    c  Class' method
    c  common blocks
    c  constant declarations
    c  constants
    c  constants
    c  constants
    c  constants (define, parameter, specparam)
    c  cursors
    c  functor definitions
    c  user-defined commands
    i  class interface
    i  imports [off]
    i  includes
    i  indexes
    i  interface contents, generic names, and operators [off]
    i  interfaces
    i  interfaces
    i  interfaces 
    n  namelists
    n  namespaces
    n  namespaces
    n  namespaces
    n  namespaces 
    n  net data types
    n  synonyms

It is just a suggesion.  :)

**Comment by jstemmer** [comment]
Yeah that's a bit unfortunate. There are several kinds with a shared prefix (import/interface, constant/class/constructor, fields/functions), so I used what was available and seemed appropriate at the time. Unfortunately changing this now would break the Tagbar integration for everyone until they update their config, so I don't think it's worth changing this now. Thanks for the suggestion.
