### ISSUE TITLE
Inconsistent field order among structs and interfaces

### ISSUE THREAD

**Issue by chenpengcheng** [jstemmer/gotags#36]
https://github.com/jstemmer/gotags/blob/3751bad226c4308b3812a362ffda82e40de731ac/tag.go#L88

This is the sample tags file generated for sarama package:

491 Messages    consumer.go 285;"   m   access:public   line:285    ntype:PartitionConsumer signature:()    type:chan *ConsumerMessage
492 Messages    consumer.go 402;"   m   access:public   ctype:partitionConsumer line:402    signature:()    type:chan *ConsumerMessage

For a struct method, the line number is after signature. For an interface method, the line number is before signature. It would be nice to keep the fields in consistent order.

**Comment by jstemmer** [comment]
Tag fields are sorted by their name, so the order is predictable. I guess I could've named the fields `type-n` and `type-c` or something similar for a better sort order, but that's a bit late now. Is this causing problems somewhere?

**Comment by blockchainian** [comment]
It is just a suggestion. I wrote a script for fzf.vim to parse tags. For the current order, I need a special case to handle it. No big deal. :)

**Comment by jstemmer** [comment]
Rather than relying on the position in the list of fields (which could always change in the future), wouldn't it be more robust to find the field by name instead?

I'd prefer not to add a special case for the order in which fields are written, this would also have to be maintained in future versions.
